# Generated by Django 5.1.4 on 2024-12-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.TextField()),
                ('test2', models.IntegerField()),
                ('test4', models.CharField()),
                ('test5', models.DecimalField(decimal_places=2, max_digits=3)),
                ('test6', models.DateField()),
                ('test7', models.TimeField()),
                ('test8', models.DateTimeField()),
                ('test9', models.BinaryField()),
                ('test10', models.BooleanField()),
            ],
        ),
    ]
