# Generated by Django 5.1.4 on 2024-12-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test13',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
