# Generated by Django 5.1.4 on 2025-01-01 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_test_test13'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testrelation1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testrelation1', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Testrelation2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testrelation2', models.CharField(max_length=20)),
                ('testrelation3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.testrelation1')),
            ],
        ),
    ]
