# Generated by Django 5.1.4 on 2025-01-01 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_testrelation1_testrelation2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testrelation3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testrelation4', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Testrelation4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testrelation5', models.CharField(max_length=20)),
                ('testrelation6', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test', to='pages.testrelation3')),
            ],
        ),
    ]
