# Generated by Django 5.1.4 on 2025-01-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_test_test4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('testmedia1', models.ImageField(upload_to='photos/%y/%m/%d')),
            ],
        ),
    ]
